version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/var/www/html
    depends_on:
      - api

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: ./frontend/Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: api
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
